# GOAL: Deploy the application to production after CI completed.

name: CD

on:
  workflow_run: 
    workflows: ["Simple Flow"]
    branches: 
      - master
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: copy the .env file
        run: cp .env.example .env

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy Container by docker-compose
        run: |
          docker-compose pull
          docker-compose up -d